#import "@preview/commute:0.3.0": node, arr, commutative-diagram
#show link: underline
#set text(font: (
  (name: "libertinus serif"),
  "Noto Serif CJK SC"
))
//#set heading(numbering: "1.")

///// ↑↑↑ SETTINGS ↑↑↑ /////

#align(center, text(17pt)[
  What I have learnt today
])

#grid(
  columns: (1fr),
  align(center)[
Author: 秦宇轩（Qin Yuxuan）\
Last complied at #datetime.today().display() \
  ],
)

///// ↑↑↑ TITLES ↑↑↑ /////

#outline()
#line(length: 100%)

///// ↑↑↑ Contents ↑↑↑ /////

= 2025

== 06-30: $F^times$ is cyclic
For finite field $F$, the multiplicative group $F^times$ is cyclic. This result can be used to prove that every finite field is gained from a quotient like $bold(F)_p [x] \/ (pi (x))$, for some prime $p$ and monic irreducible $pi (x)$.

*Main idea*: a group $G$ is cyclic iff there is an element $g$ such that $h = g^k$ for any other element $h$ and some $k$, so we must have $"ord" g = |G|$. But by Lagrange theorem we alyways have $"ord" g | |G|$ for any $g$ in $G$, so it suffices to prove $|G| <= "ord" g$. Thanks to the lemma below, we have $h^("ord" g) = 1$ for all $h$. So the polynomial $x^("ord" g) = 1$ has $|F^times|$ roots, which implies $|F^times| <= "ord" g$.

*Lemma*: In finite ablian group, the order of every element divides the maximal order. (It's fun to prove)

_Ref._ #link("https://kconrad.math.uconn.edu/blurbs/galoistheory/finitefields.pdf")[Finite Field by Conrad].

== 07-05: Compact theorem (by Ultraproduct)
- Ultraproduct: suppose $(A_i)_(i in I)$ is a bunch of structure in language $L$, then we can construct a new structure $cal(A)$ using them, provieded am ultrafilter $ cal(U)$ on $I$:
$ cal(A) := product_cal(U) A_i := (product_(i in I) A_i) \/ ~_cal(U). $

- Los theorem: A formula is ture in an ultraproduct, if and only if this formula is ture in _many_ smaller models which are used to made that ultraproduct. ("many" is defined by the ultrafilter.)
- Proof of Compact theorem: The model you want is the ultraproduct $product_cal(U) A_i$ where $(A_i) _(i in I)$, which is indexed by the set $I$ of all finite sub-theory of given theory $T$, are models of $i in I$ (by assumption these models must exist). To prove all formula $phi$ in $T$ are vaild in that ultraproduct, one consult for Los theorem. (The ultrafilter needed by Los theorem can just be solved out by your desire of "makeing $cal(A)$ a model of $T$".)

A little interesting result: Suppose $cal(U)_A$ is an ultrafilter generated by $A$ on $I$ (thus is priciple), then
$ {cal(U)_A subset B: B "ultrafilter on I"} tilde.eq {V: V "ultrafilter on A"}. $

This can be used to prove every priciple ultrafilter is generated by a singleton in $cal(P)(I)$ i.e., by a single subset of $I$, or equivalentlly, every non-principle ultrafilter must contain the Frechet filter (consists of precisely all "cofinite" subsets of $I$) as a subset.

_Ref._ #link("https://link.springer.com/book/10.1007/978-3-319-92414-4")[Sets, Models and Proofs by Ieke Moerdijk and Jaap van Oosten].
